Repository shadokos/kfs, pull requests merged in 2024-04, with the labels that each got.

#145 FIX #144
  src/memory/cache.zig
Labels: fix, Rework

#149 FIX #143
  src/logger.zig
  src/tty/tty.zig
Labels: fix, tty

#156 REWORK 0.12
  .github/workflows/ci.yml
  build.zig
  src/drivers/acpi/acpi.zig
  src/drivers/ps2/ps2.zig
  src/ft/Random.zig
  src/ft/array_list.zig
  src/ft/fmt.zig
  src/ft/math.zig
  src/linker.ld
  src/memory.zig
  src/memory/bitmap.zig
  src/memory/buddy_allocator.zig
  src/memory/cache.zig
  src/memory/physical_memory.zig
  src/memory/slab.zig
  src/memory/virtual_memory.zig
  src/memory/virtual_space_allocator.zig
  src/multiboot.zig
  src/shell.zig
  src/shell/builtins.zig
  src/shell/token.zig
  src/shell/utils.zig
  src/tty/keyboard.zig
  src/tty/keyboard/keymap.zig
  src/tty/themes.zig
  src/tty/tty.zig
  src/tty/vt100.zig
Labels: Rework
