Repository shadokos/kfs, pull requests merged in 2024-03, with the labels that each got.

#97 ADD permissions in mapping:
  src/memory.zig
  src/memory/mapping.zig
  src/memory/virtual_page_allocator.zig
  src/multiboot.zig
  src/shell/builtins.zig
  src/shell/utils.zig
Labels: update, memory

#107 FIX #106
  src/tty/tty.zig
Labels: fix, tty

#105 UPDATE gdt
  src/boot.zig
  src/gdt.zig
  src/linker.ld
Labels: update

#117 REWORK io ports:
  Makefile
  src/cpu.zig
  src/drivers/acpi/acpi.zig
  src/drivers/ps2/ps2.zig
  src/drivers/vga/text.zig
  src/io/ports.zig
Labels: Rework

#120 FIX #119:
  src/tty/tty.zig
Labels: fix

#124 ADD CI build:
  .github/workflows/build.yml
  Makefile
Labels: feature

#128 FIX #127
  .git-hooks/pre-commit
  .github/pre-commit
  .github/workflows/ci.yml
  build.zig
Labels: fix, Rework
