Repository shadokos/kfs, pull requests merged in 2024-02, with the labels that each got.

#48 fix #43 and #49
  src/tty/tty.zig
Labels: unexpected behaviour

#51 FIX is_echoctl
  src/tty/tty.zig
Labels: fix

#56 ADD panic function:
  src/boot.zig
Labels: feature

#58 FIX multiboot
  src/multiboot.zig
Labels: fix

#62 ADD functions to libft:
  src/ft/math.zig
  src/ft/mem.zig
Labels: feature

#63 ADD mmap command:
  src/shell/builtins.zig
  src/shell/helpers.zig
  src/shell/utils.zig
Labels: feature

#68 FIX parseInt
  src/ft/fmt.zig
Labels: fix

#73 FIX hexdump
  src/shell/builtins.zig
  src/shell/utils.zig
Labels: fix

#74 FIX #54
  src/multiboot.zig
Labels: fix

#95 fix #94
  src/tty/themes.zig
Labels: fix

#96 FIX PS/2 Driver:
  src/drivers/ps2/ps2.zig
Labels: fix
