Repository shadokos/kfs, pull requests merged in 2024-01, with the labels that each got.

#17 FIX: issue #16
  src/tty/tty.zig
Labels: fix

#18 ADD docker
  Makefile
  dockerfile
Labels: feature

#20 FIX #19:
  src/tty/tty.zig
Labels: Rework

#29 FIX tty input
  src/ft/math.zig
  src/tty/tty.zig
  src/tty/vt100.zig
Labels: fix

#31 FIX kb_read:
  src/tty/keyboard.zig
Labels: fix

#32 ADD multiboot_info:
  build.zig
  src/boot.zig
  src/c_headers.zig
  src/c_headers/multiboot.h
  src/kernel.zig
Labels: feature

#41 FIX: issue #30
  build.zig
  src/tty/keyboard.zig
  src/tty/tty.zig
  src/tty/vt100.zig
Labels: update
